### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s3-evaluacion-intermedia-elisamartinb#1]
Really good job @elisamartinb !!

Some tips to improve it

- [x] Move `li` outside 'Pokemon' component, this way it will be a simple card that can be used anywhere, not only inside a `ul`
- [x] Since types map function only has a line that is returned you can simplify it removing brackets and return
- [x] Split styles (one file per component)
- [x] Review metadata on index.html (lang, title...)
- [x] Clean and indent

Go for it!

**Comment by elisamartinb** [comment]
Hi @nasivuela !! Im working on it...but regarding the first improvement about moving `li` outside Pokemon I dont fully understand it..because Pokemon will be a `li` anyway, right?

**Comment by nasivuela** [comment]
Well, the point is to could use `Pokemon` anywhere, not only as an element inside a list.

**Comment by elisamartinb** [comment]
Done @nasivuela !!😁 
I also added Route and the input for searching pokemons, can you check it please?🤓

**Comment by nasivuela** [comment]
Well done!!

![](https://media.giphy.com/media/115quIlEidBFPq/giphy.gif)

When adding a third party library as react-router-dom, do not forget to add it to the package.json `npm install --save ...`
